[dev] 
  publish = "www"
  functions = "functions"
  
[build] 
  publish = "www"
  command = "echo No build command yet!"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[template.environment]
  CONSUMER_KEY = "feZAfsS2lYRLGU1t8W4-xQ=="
  CONSUMER_SECRET = "87ucXGjexPDo77144Gl7d7cNFminvt2gpFLf9vT3IgY="